Rails/Proyecto AS/Arquitectura/config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'
  root 'inicio#index' 
  devise_for :users
  resources :peticions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Proyecto AS/Arquitectura/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize( user )
   
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

Rails/Proyecto AS/Arquitectura/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/Proyecto AS/Arquitectura/app/models/peticion.rb
class Peticion < ApplicationRecord
end

Rails/Proyecto AS/Arquitectura/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
        
end

Rails/Proyecto AS/Arquitectura/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

Rails/Proyecto AS/Arquitectura/app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

Rails/Proyecto AS/Arquitectura/app/controllers/peticions_controller.rb
class PeticionsController < ApplicationController
  before_action :set_peticion, only: [:show, :edit, :update, :destroy]

  # GET /peticions
  # GET /peticions.json
  def index
    @peticions = Peticion.all
  end

  # GET /peticions/1
  # GET /peticions/1.json
  def show
  end

  # GET /peticions/new
  def new
    @peticion = Peticion.new
  end

  # GET /peticions/1/edit
  def edit
  end

  # POST /peticions
  # POST /peticions.json
  def create
    @peticion = Peticion.new(peticion_params)

    respond_to do |format|
      if @peticion.save
        format.html { redirect_to @peticion, notice: 'Peticion was successfully created.' }
        format.json { render :show, status: :created, location: @peticion }
      else
        format.html { render :new }
        format.json { render json: @peticion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peticions/1
  # PATCH/PUT /peticions/1.json
  def update
    respond_to do |format|
      if @peticion.update(peticion_params)
        format.html { redirect_to @peticion, notice: 'Peticion was successfully updated.' }
        format.json { render :show, status: :ok, location: @peticion }
      else
        format.html { render :edit }
        format.json { render json: @peticion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peticions/1
  # DELETE /peticions/1.json
  def destroy
    @peticion.destroy
    respond_to do |format|
      format.html { redirect_to peticions_url, notice: 'Peticion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peticion
      @peticion = Peticion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peticion_params
      params.require(:peticion).permit(:Tipo_de_documento, :Nombre, :Apellido, :Direccion, :Correo, :Pais, :ciudad, :tipoSolicitud, :Detalle)
    end
end

Rails/Proyecto AS/Arquitectura/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Proyecto AS/Arquitectura/app/helpers/inicio_helper.rb
module InicioHelper
end

Rails/Proyecto AS/Arquitectura/app/helpers/peticions_helper.rb
module PeticionsHelper
end

Rails/Proyecto AS/Arquitectura/app/views/inicio/index.html.erb
<h1>Bienvenido al sistema de ingreso de PQR</h1>
<%= link_to 'Click aca para ingresar tu PQR', new_peticion_path %>

Rails/Proyecto AS/Arquitectura/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AS</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
    <div id="wrapper">

      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <li class="sidebar-brand">
                  <a href="#">
                      Panel De Control
                  </a>
              </li>
               <li>
                  <%= link_to 'Nuevo PQRS', new_peticion_path, :class => 'sidebar-brand' %>
              </li>
              <li>
                  <%= link_to 'Ver PQRS', peticions_path, :class => 'sidebar-brand' %>
              </li>
              <li>
                  
                  <%= link_to 'Enviar PQRS', peticions_path, :class => 'sidebar-brand' %>
              </li>
              <li>
                  
                  <%= link_to 'Responder PQRS', peticions_path, :class => 'sidebar-brand' %>
              </li>
             
          </ul>
      </div>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
          <div class="container-fluid">    
      <!-- Arriba navbar -->
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
                <a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">Interactuar</a>
                  <div class="container">
                    <a class="navbar-brand" href="#">
                      <img src="http://placehold.it/300x60?text=Logo" width="0" height="30" alt="">
                      <%= link_to 'SISTEMA PQR', inicio_index_path, :class => 'navbar-brand' %>
                      
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                      <ul class="navbar-nav ml-auto">
                        
                            <p class="navbar-text pull-right">
                                    <% if user_signed_in? %>
                                    Logged in as <strong><%= current_user.email %></strong>.
                                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                                    <% else %>
                                    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                                    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                                    <% end %>
                                    </p>
                        
                      </ul>
                    </div>
                  </div>
                </nav>
                <div class="p-3 mb-2 bg-light text-dark">
                      <%= yield %>
                    </div>
                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>
          </div>
      </div>
      <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

 

  <!-- Menu Toggle Script -->
  <script>
  $("#menu-toggle").click(function(e) {
    
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
      
      
     
  });
  </script>

  </div>




  </body>
</div>
</html>

Rails/Proyecto AS/Arquitectura/app/views/peticions/_form.html.erb
<%= form_with(model: peticion, local: true) do |form| %>
  <% if peticion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peticion.errors.count, "error") %> prohibited this peticion from being saved:</h2>

      <ul>
      <% peticion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Tipo_de_documento %>
    <%= form.text_field :Tipo_de_documento, id: :peticion_Tipo_de_documento %>
  </div>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :Nombre, id: :peticion_Nombre %>
  </div>

  <div class="field">
    <%= form.label :Apellido %>
    <%= form.text_field :Apellido, id: :peticion_Apellido %>
  </div>

  <div class="field">
    <%= form.label :Correo %>
    <%= form.text_field :Correo, id: :peticion_Correo %>
  </div>

  <div class="field">
    <%= form.label :ciudad %>
    <%= form.text_field :ciudad, id: :peticion_ciudad %>
  </div>

  <div class="field">
    <%= form.label :Detalle %>
    <%= form.text_area :Detalle, id: :peticion_Detalle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rails/Proyecto AS/Arquitectura/app/views/peticions/edit.html.erb
<%= render 'form', peticion: @peticion %>

<%= link_to 'Show', @peticion %> |
<%= link_to 'Back', peticions_path %>

Rails/Proyecto AS/Arquitectura/app/views/peticions/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Peticions</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col" >Tipo de documento</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">Direccion</th>
      <th scope="col">Correo</th>
      <th scope="col">Pais</th>
      <th scope="col">Ciudad</th>
      <th scope="col">Tiposolicitud</th>
      <th scope="col">Detalle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peticions.each do |peticion| %>
      <tr>
        <td><%= peticion.Tipo_de_documento %></td>
        <td><%= peticion.Nombre %></td>
        <td><%= peticion.Apellido %></td>
        <td><%= peticion.Direccion %></td>
        <td><%= peticion.Correo %></td>
        <td><%= peticion.Pais %></td>
        <td><%= peticion.ciudad %></td>
        <td><%= peticion.tipoSolicitud %></td>
        <td><%= peticion.Detalle %></td>
        <td><%= link_to 'Show', peticion %></td>
        <td><%= link_to 'Edit', edit_peticion_path(peticion) %></td>
        <td><%= link_to 'Destroy', peticion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
<%= link_to 'New Peticion', new_peticion_path %>
-->

Rails/Proyecto AS/Arquitectura/app/views/peticions/new.html.erb
<%= render 'form', peticion: @peticion %>

<%= link_to 'Back', peticions_path %>

Rails/Proyecto AS/Arquitectura/app/views/peticions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo de documento:</strong>
  <%= @peticion.Tipo_de_documento %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @peticion.Nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @peticion.Apellido %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @peticion.Direccion %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @peticion.Correo %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @peticion.Pais %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @peticion.ciudad %>
</p>

<p>
  <strong>Tiposolicitud:</strong>
  <%= @peticion.tipoSolicitud %>
</p>

<p>
  <strong>Detalle:</strong>
  <%= @peticion.Detalle %>
</p>

<%= link_to 'Edit', edit_peticion_path(@peticion) %> |
<%= link_to 'Back', peticions_path %>